name: Lint Commit, Build Binaries and Run Unit Test

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sed -i -E "s/([']docker:.+)/Dockerfile/" ./action.yml
      - run: echo -n '' > .dockerignore
      - uses: ./
        with:
          configFile: './.commitlintrc.yml'
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Test
      run: dotnet test
