name: On Push

on: [push]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          first-parent: false
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'

  build:
    needs: [lint-commit]
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Lint Code
      run: dotnet fsharplint lint --lint-config fsharplint.json
    - name: Run Test
      run: dotnet test
