name: On Pull Request

on: [pull_request]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true

  lint-code:
    needs: lint-commit
    # So that we don't juggle with different OS for accessing the right path...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1
      # For some reasons the path is kinda messed up...
      # Doesn't consider the .config folder =|
      - name: Restore tools
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet tool install -g dotnet-fsharplint --version 0.13.3
      - name: Run F# Linter
        run: dotnet fsharplint lint --lint-config fsharplint.json MessingUp.sln

  run-test:
    needs: [lint-commit, lint-code]
    strategy:
      matrix:
        # If possible, try to figure out how to leverage the 3 main OSs with the docker-compose command below
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: [3.1.201]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose --file "./MessingUp.Tests/docker-compose.yml" up --detach
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run Tests
        run: dotnet test
