name: On Pull Request

on: [pull_request]

jobs:

  lint-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: './.commitlintrc.yml'
          firstParent: false
          failOnWarnings: true

  lint-code:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [2.1.0]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Restore tools
        run: dotnet tool restore
      - name: Run F# Linter
        run: dotnet fsharplint lint --lint-config fsharplint.json MessingUp.sln
