name: On Tag Master

on:
  push:
    tags:
      - '*' # Publish on any new tag

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}
