name: On Tag Master

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    # branches:
    # - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        source-url: https://api.nuget.org/v3/index.json
    - name: Get Tag Version
      id: getversion
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
    - name: Build .NET Project
      run: dotnet build --configuration Release -p:Version=${{steps.getversion.outputs.version}} ./MessingUp/MessingUp.fsproj
    - name: Generate NuGet Package from .NET Project
      run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{steps.getversion.outputs.version}} ./MessingUp/MessingUp.fsproj --output .
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish NuGet Package
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY}}
